name: boot-case build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build admin server docker and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/boot-admin-server.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/boot-admin-server:v1
      - name: Build boot prometheus docker and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/boot-prometheus.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/boot-prometheus:v1
      - name: Build boot eureka docker and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/boot-eureka-server.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/boot-eureka-server:v1